name: Deploy Next.js Application

on:
  push:
    branches:
      - main  

jobs:
  check-correct-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' 

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

  deploy-server:
    needs: check-correct-build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd $DEPLOY_PATH
            git pull origin main
            npm install
            npm run build
            pm2 restart funkotracker
          EOF
